# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.grand_exchange as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    grand_exchange_0 = module_0.GrandExchange(none_type_0)
    list_0 = grand_exchange_0.get_categories()
    assert (
        list_0
        == '[{"id": 0, "name": "Miscellaneous"}, {"id": 1, "name": "Ammo"}, {"id": 2, "name": "Arrows"}, {"id": 3, "name": "Bolts"}, {"id": 4, "name": "Construction materials"}, {"id": 5, "name": "Construction products"}, {"id": 6, "name": "Cooking ingredients"}, {"id": 7, "name": "Costumes"}, {"id": 8, "name": "Crafting materials"}, {"id": 9, "name": "Familiars"}, {"id": 10, "name": "Farming produce"}, {"id": 11, "name": "Fletching materials"}, {"id": 12, "name": "Food and Drink"}, {"id": 13, "name": "Herblore materials"}, {"id": 14, "name": "Hunting equipment"}, {"id": 15, "name": "Hunting Produce"}, {"id": 16, "name": "Jewellery"}, {"id": 17, "name": "Mage armour"}, {"id": 18, "name": "Mage weapons"}, {"id": 19, "name": "Melee armour - low level"}, {"id": 20, "name": "Melee armour - mid level"}, {"id": 21, "name": "Melee armour - high level"}, {"id": 22, "name": "Melee weapons - low level"}, {"id": 23, "name": "Melee weapons - mid level"}, {"id": 24, "name": "Melee weapons - high level"}, {"id": 25, "name": "Mining and Smithing"}, {"id": 26, "name": "Potions"}, {"id": 27, "name": "Prayer armour"}, {"id": 28, "name": "Prayer materials"}, {"id": 29, "name": "Range armour"}, {"id": 30, "name": "Range weapons"}, {"id": 31, "name": "Runecrafting"}, {"id": 32, "name": "Runes, Spells and Teleports"}, {"id": 33, "name": "Seeds"}, {"id": 34, "name": "Summoning scrolls"}, {"id": 35, "name": "Tools and containers"}, {"id": 36, "name": "Woodcutting product"}, {"id": 37, "name": "Pocket items"}, {"id": 38, "name": "Stone spirits"}, {"id": 39, "name": "Salvage"}, {"id": 40, "name": "Firemaking products"}, {"id": 41, "name": "Archaeology materials"}, {"id": 42, "name": "Wood spirits"}, {"id": 43, "name": "Necromancy armour"}]'
    )
    grand_exchange_0.get_number_of_items_by_category(list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    grand_exchange_0 = module_0.GrandExchange(none_type_0)
    grand_exchange_0.get_item_graph(grand_exchange_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    grand_exchange_0 = module_0.GrandExchange(none_type_0)
    grand_exchange_0.get_item_detail(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    bool_0 = True
    grand_exchange_0 = module_0.GrandExchange(none_type_0)
    grand_exchange_0.get_items(bool_0, bool_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    grand_exchange_0 = module_0.GrandExchange(none_type_0)
    grand_exchange_0.get_last_update()
