# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.utils.validation as module_0
import builtins as module_1


def test_case_0():
    bool_0 = False
    module_0.is_boolean(bool_0, bool_0)
    str_0 = "divination"
    with pytest.raises(ValueError):
        module_0.is_positive_int(bool_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.is_positive_int(none_type_0, none_type_0)


def test_case_2():
    none_type_0 = None
    str_0 = "{r\n4{17q-w"
    module_0.is_non_empty_str(str_0, str_0)
    str_1 = "3D2x,je("
    with pytest.raises(TypeError):
        module_0.is_boolean(none_type_0, str_1)


def test_case_3():
    bool_0 = False
    none_type_0 = None
    with pytest.raises(TypeError):
        module_0.is_non_empty_str(bool_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "Potions"
    bool_0 = True
    module_0.is_boolean(bool_0, bool_0)
    none_type_0 = module_0.is_positive_int(bool_0, str_0)
    str_1 = " "
    module_0.is_non_empty_str(str_1, none_type_0)
    none_type_1 = None
    str_2 = "0_"
    module_0.is_non_empty_str(none_type_1, str_2)


@pytest.mark.xfail(strict=True)
def test_case_5():
    object_0 = module_1.object()
    str_0 = "KBD7pQVl?p\x0cFdTd"
    module_0.is_non_empty_str(str_0, str_0)
    str_1 = ""
    module_0.is_non_empty_str(str_1, object_0)
