# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.bestiary as module_0
import runescape_api.rs3.models.beast_summary as module_1


def test_case_0():
    none_type_0 = None
    module_0.Bestiary(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    bestiary_0 = module_0.Bestiary(none_type_0)
    bestiary_0.get_beast_by_id(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 2622
    bestiary_0 = module_0.Bestiary(int_0)
    bestiary_0.get_slayer_categories()


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "r0K]HZ"
    set_0 = {str_0, str_0, str_0}
    int_0 = 931
    str_1 = 'Leci"{i\\c}='
    beast_summary_0 = module_1.BeastSummary(int_0, str_1, int_0)
    var_0 = beast_summary_0.__eq__(set_0)
    var_1 = var_0.__repr__()
    bestiary_0 = module_0.Bestiary(var_1)
    bestiary_0.get_weakness()


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = True
    bestiary_0 = module_0.Bestiary(bool_0)
    bestiary_0.get_area_names()
