# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.hiscores as module_0


def test_case_0():
    none_type_0 = None
    module_0.Hiscores(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    list_0 = []
    hiscores_0 = module_0.Hiscores(list_0)
    hiscores_0.get_hardcore_ironman_lite(hiscores_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 19
    bool_0 = True
    hiscores_0 = module_0.Hiscores(bool_0)
    bool_1 = True
    hiscores_0.get_group_ironman(bool_0, bool_1, int_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    list_0 = []
    hiscores_0 = module_0.Hiscores(list_0)
    hiscores_0.get_leagues_lite(hiscores_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    str_0 = '\r{sd:91j"z)h\x0bi<'
    hiscores_0.get_clan_members_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    list_0 = []
    hiscores_0 = module_0.Hiscores(list_0)
    str_0 = "E?[^.)v\\l"
    hiscores_0.get_hiscores_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    none_type_0 = None
    str_0 = ""
    hiscores_0 = module_0.Hiscores(str_0)
    hiscores_0.get_ironman_lite(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    str_0 = ""
    hiscores_0 = module_0.Hiscores(str_0)
    hiscores_0.get_user_clan_ranking(str_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    str_0 = "2)\tU\x0cq-e"
    hiscores_0 = module_0.Hiscores(str_0)
    hiscores_0.get_hiscores_details()


@pytest.mark.xfail(strict=True)
def test_case_9():
    str_0 = ""
    int_0 = -1692
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(str_0)
    bool_0 = False
    int_1 = 730
    hiscores_0.get_bosses_groups(none_type_0, int_0, bool_0, int_1)


@pytest.mark.xfail(strict=True)
def test_case_10():
    int_0 = -1692
    hiscores_0 = module_0.Hiscores(int_0)
    hiscores_0.get_hiscores_details(int_0)


@pytest.mark.xfail(strict=True)
def test_case_11():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    bool_0 = True
    int_0 = 433
    hiscores_0.get_ranking(bool_0, hiscores_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_12():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    hiscores_0.get_user_ranking(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_13():
    str_0 = "[\njE "
    hiscores_0 = module_0.Hiscores(str_0)
    hiscores_0.get_seasonal_ranking(str_0)


@pytest.mark.xfail(strict=True)
def test_case_14():
    str_0 = "[\njE "
    hiscores_0 = module_0.Hiscores(str_0)
    bool_0 = True
    hiscores_0.get_seasonal_ranking(str_0, bool_0)
