# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.runemetrics as module_0


def test_case_0():
    none_type_0 = None
    module_0.Runemetrics(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 2025
    runemetrics_0 = module_0.Runemetrics(int_0)
    str_0 = "8qy["
    runemetrics_0.get_profile(runemetrics_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    runemetrics_0 = module_0.Runemetrics(none_type_0)
    int_0 = -1995
    runemetrics_0.get_monthly_xp(runemetrics_0, int_0)
