# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.bestiary as module_0


def test_case_0():
    none_type_0 = None
    module_0.Bestiary(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 1031
    none_type_0 = None
    bestiary_0 = module_0.Bestiary(none_type_0)
    bestiary_0.get_beast_by_id(int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "?"
    bestiary_0 = module_0.Bestiary(str_0)
    bestiary_0.get_weakness()


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    bestiary_0 = module_0.Bestiary(none_type_0)
    bestiary_0.get_slayer_categories()


@pytest.mark.xfail(strict=True)
def test_case_4():
    int_0 = 893
    bestiary_0 = module_0.Bestiary(int_0)
    bestiary_0.get_area_names()
