# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.utils.validation as module_0


def test_case_0():
    bool_0 = True
    str_0 = ">[q\rNg;"
    none_type_0 = module_0.is_positive_int(bool_0, str_0)
    module_0.is_boolean(bool_0, bool_0)
    with pytest.raises(TypeError):
        module_0.is_non_empty_str(none_type_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    str_0 = "2%cvP"
    none_type_0 = module_0.is_non_empty_str(str_0, bool_0)
    module_0.is_positive_int(none_type_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 410
    str_0 = "hns"
    none_type_0 = None
    module_0.is_non_empty_str(str_0, none_type_0)
    bool_0 = False
    str_1 = "OZ'U(Ii6>kcJw6d_?"
    module_0.is_boolean(bool_0, str_1)
    module_0.is_boolean(int_0, int_0)


def test_case_3():
    int_0 = 415
    with pytest.raises(TypeError):
        module_0.is_non_empty_str(int_0, int_0)


def test_case_4():
    bool_0 = False
    module_0.is_boolean(bool_0, bool_0)
    bool_1 = False
    str_0 = "aYgrx"
    with pytest.raises(TypeError):
        module_0.is_non_empty_str(bool_1, str_0)


def test_case_5():
    bool_0 = False
    str_0 = "poisonous"
    with pytest.raises(ValueError):
        module_0.is_positive_int(bool_0, str_0)


def test_case_6():
    str_0 = ""
    with pytest.raises(ValueError):
        module_0.is_non_empty_str(str_0, str_0)
