# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.hiscores as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -979
    hiscores_0 = module_0.Hiscores(int_0)
    hiscores_0.get_hiscores_details()


def test_case_1():
    none_type_0 = None
    module_0.Hiscores(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    set_0 = set()
    hiscores_0 = module_0.Hiscores(set_0)
    int_0 = 37
    hiscores_0.get_user_ranking(int_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "\r\x0cRNkLlNhj0"
    hiscores_0 = module_0.Hiscores(str_0)
    hiscores_0.get_clan_members_lite(hiscores_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    int_0 = 702
    bool_0 = True
    bool_1 = True
    hiscores_0.get_group_ironman(bool_0, int_0, bool_1, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = "{}L%AomPw~"
    hiscores_0 = module_0.Hiscores(str_0)
    hiscores_0.get_hiscores_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    int_0 = -952
    hiscores_0 = module_0.Hiscores(int_0)
    hiscores_0.get_leagues_lite(int_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    int_0 = -979
    hiscores_0 = module_0.Hiscores(int_0)
    str_0 = "mVe|xgJMAA\\=\rfi\x0b%"
    hiscores_0.get_hardcore_ironman_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    set_0 = set()
    hiscores_0 = module_0.Hiscores(set_0)
    bool_0 = True
    hiscores_0.get_bosses_groups(set_0, hiscores_0, bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_9():
    int_0 = 28
    hiscores_0 = module_0.Hiscores(int_0)
    hiscores_0.get_user_clan_ranking(int_0)


@pytest.mark.xfail(strict=True)
def test_case_10():
    int_0 = -979
    hiscores_0 = module_0.Hiscores(int_0)
    bool_0 = True
    hiscores_0.get_hiscores_details(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_11():
    int_0 = -979
    hiscores_0 = module_0.Hiscores(int_0)
    str_0 = "H"
    hiscores_0.get_seasonal_ranking(str_0, hiscores_0)


@pytest.mark.xfail(strict=True)
def test_case_12():
    int_0 = -990
    hiscores_0 = module_0.Hiscores(int_0)
    int_1 = 475
    hiscores_0.get_ranking(hiscores_0, int_1, int_0)


@pytest.mark.xfail(strict=True)
def test_case_13():
    float_0 = -1034.099388
    hiscores_0 = module_0.Hiscores(float_0)
    hiscores_0.get_ironman_lite(hiscores_0)


@pytest.mark.xfail(strict=True)
def test_case_14():
    bool_0 = True
    hiscores_0 = module_0.Hiscores(bool_0)
    str_0 = "4\nUum"
    hiscores_0.get_seasonal_ranking(str_0)
