# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.runemetrics as module_0


def test_case_0():
    none_type_0 = None
    module_0.Runemetrics(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    runemetrics_0 = module_0.Runemetrics(bool_0)
    runemetrics_0.get_profile(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"\x8a\x9f\xc8\x87\nx\xb4*jG\xa1\xceT\xe6\x851\xf4"
    runemetrics_0 = module_0.Runemetrics(bytes_0)
    int_0 = 79
    runemetrics_0.get_monthly_xp(runemetrics_0, int_0)
