# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.bestiary as module_0
import runescape_api.rs3.models.beast as module_1
import runescape_api.rs3.models.beast_summary as module_2


def test_case_0():
    str_0 = ""
    module_0.Bestiary(str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    bool_0 = True
    str_0 = "$!Mg,<0#J"
    str_1 = "I\x0cr"
    bool_1 = True
    bool_2 = False
    str_2 = "\x0b{"
    bool_3 = True
    bool_4 = False
    str_3 = "~H"
    str_4 = "B\x0bZe]\tZ}#J"
    list_0 = [str_4]
    beast_0 = module_1.Beast(
        bool_1,
        none_type_0,
        bool_2,
        bool_2,
        bool_2,
        bool_0,
        str_1,
        none_type_0,
        bool_2,
        none_type_0,
        str_2,
        str_0,
        none_type_0,
        str_2,
        bool_3,
        bool_4,
        bool_0,
        str_3,
        list_0,
        str_0,
    )
    var_0 = beast_0.__repr__()
    var_1 = var_0.__eq__(str_1)
    var_2 = var_1.__eq__(str_0)
    bestiary_0 = module_0.Bestiary(var_2)
    bestiary_0.get_slayer_categories()


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    str_0 = ""
    beast_summary_0 = module_2.BeastSummary(bool_0, str_0, bool_0)
    var_0 = beast_summary_0.__eq__(beast_summary_0)
    bestiary_0 = module_0.Bestiary(var_0)
    bestiary_0.get_beast_by_id(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = ""
    var_0 = str_0.__repr__()
    bestiary_0 = module_0.Bestiary(var_0)
    bestiary_1 = module_0.Bestiary(bestiary_0)
    bestiary_1.get_area_names()


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = False
    str_0 = ""
    beast_summary_0 = module_2.BeastSummary(bool_0, str_0, bool_0)
    var_0 = beast_summary_0.__eq__(beast_summary_0)
    bestiary_0 = module_0.Bestiary(var_0)
    bestiary_0.get_weakness()
