# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.utils.validation as module_0
import builtins as module_1


def test_case_0():
    bool_0 = False
    int_0 = -1641
    str_0 = 'e7bO<7>p6u1"8\x0cZ?D?=g'
    module_0.is_non_empty_str(str_0, str_0)
    with pytest.raises(ValueError):
        module_0.is_positive_int(int_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    str_0 = "GTQl2eXSD/l|\tJ^l'"
    str_1 = "h,-\x0bb*!3cf"
    module_0.is_boolean(bool_0, str_1)
    module_0.is_positive_int(bool_0, str_0)
    module_0.is_positive_int(str_0, str_0)


def test_case_2():
    object_0 = module_1.object()
    dict_0 = {object_0: object_0}
    bool_0 = False
    with pytest.raises(TypeError):
        module_0.is_non_empty_str(bool_0, dict_0)


def test_case_3():
    int_0 = -1315
    str_0 = 'QtP":/e!ClM'
    str_1 = "C\ryL\rU"
    module_0.is_non_empty_str(str_1, int_0)
    with pytest.raises(TypeError):
        module_0.is_boolean(int_0, str_0)


def test_case_4():
    str_0 = ""
    str_1 = "_i\r@1'^cn9tWebH' "
    with pytest.raises(ValueError):
        module_0.is_non_empty_str(str_0, str_1)
