# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.bestiary as module_0
import runescape_api.rs3.models.beast_summary as module_1


def test_case_0():
    bool_0 = True
    module_0.Bestiary(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = 4687
    str_0 = "^;2ONK)H9\\~@1C"
    str_1 = 'lea"WHX_Zes'
    beast_summary_0 = module_1.BeastSummary(int_0, str_0, str_1)
    bestiary_0 = module_0.Bestiary(beast_summary_0)
    bestiary_0.get_area_names()


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    bestiary_0 = module_0.Bestiary(bool_0)
    bestiary_0.get_slayer_categories()


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    bestiary_0 = module_0.Bestiary(bool_0)
    bestiary_0.get_weakness()


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = False
    bestiary_0 = module_0.Bestiary(bool_0)
    bestiary_0.get_beast_by_id(bool_0)
