# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.runemetrics as module_0


def test_case_0():
    str_0 = "Kc{H"
    module_0.Runemetrics(str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    bool_0 = False
    runemetrics_0 = module_0.Runemetrics(none_type_0)
    runemetrics_0.get_profile(none_type_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    runemetrics_0 = module_0.Runemetrics(bool_0)
    runemetrics_0.get_monthly_xp(bool_0, bool_0)
