# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.hiscores as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = ">"
    hiscores_0 = module_0.Hiscores(str_0)
    bool_0 = False
    hiscores_0.get_hiscores_details(bool_0)


def test_case_1():
    none_type_0 = None
    module_0.Hiscores(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = -2162
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    hiscores_0.get_ranking(int_0, none_type_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    list_0 = []
    hiscores_0 = module_0.Hiscores(list_0)
    str_0 = "X'n(H98oKeh2/0qb"
    hiscores_0.get_leagues_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    int_0 = -2162
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    hiscores_0.get_user_ranking(int_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    str_0 = "dx<,SN"
    hiscores_0.get_hiscores_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    str_0 = "`Q^8WFl3pic"
    hiscores_0.get_ironman_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    str_0 = ">"
    hiscores_0 = module_0.Hiscores(str_0)
    bool_0 = True
    hiscores_0.get_hiscores_details(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    str_0 = ">"
    hiscores_0 = module_0.Hiscores(str_0)
    none_type_0 = None
    int_0 = -375
    bool_0 = True
    hiscores_0.get_group_ironman(none_type_0, hiscores_0, int_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_9():
    str_0 = ">"
    hiscores_0 = module_0.Hiscores(str_0)
    hiscores_0.get_clan_members_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_10():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    int_0 = 2882
    hiscores_0.get_user_clan_ranking(int_0)


@pytest.mark.xfail(strict=True)
def test_case_11():
    str_0 = ">"
    hiscores_0 = module_0.Hiscores(str_0)
    bool_0 = False
    int_0 = 22
    hiscores_0.get_bosses_groups(hiscores_0, bool_0, int_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_12():
    str_0 = ">"
    hiscores_0 = module_0.Hiscores(str_0)
    str_1 = "q"
    hiscores_0.get_hardcore_ironman_lite(str_1)


@pytest.mark.xfail(strict=True)
def test_case_13():
    str_0 = ">"
    hiscores_0 = module_0.Hiscores(str_0)
    str_1 = "q"
    hiscores_0.get_seasonal_ranking(str_1)


def test_case_14():
    none_type_0 = None
    module_0.Hiscores(none_type_0)
