# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.bestiary as module_0


def test_case_0():
    str_0 = "p{"
    module_0.Bestiary(str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = -2003
    bool_0 = True
    bestiary_0 = module_0.Bestiary(bool_0)
    bestiary_0.get_beast_by_id(int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    bestiary_0 = module_0.Bestiary(bool_0)
    bestiary_0.get_weakness()


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    bestiary_0 = module_0.Bestiary(bool_0)
    bestiary_0.get_area_names()


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "p{"
    bestiary_0 = module_0.Bestiary(str_0)
    bestiary_0.get_slayer_categories()
