# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.hiscores as module_0


def test_case_0():
    bool_0 = True
    module_0.Hiscores(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    complex_0 = -2876.798 - 34.8j
    hiscores_0 = module_0.Hiscores(complex_0)
    int_0 = -3841
    int_1 = -520
    bool_0 = False
    hiscores_0.get_ranking(int_0, int_1, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    list_0 = []
    hiscores_0 = module_0.Hiscores(list_0)
    hiscores_0.get_hardcore_ironman_lite(list_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = -1060
    hiscores_0 = module_0.Hiscores(int_0)
    str_0 = "az%~syG$cE;L\n"
    hiscores_0.get_clan_members_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    list_0 = []
    hiscores_0 = module_0.Hiscores(list_0)
    hiscores_0.get_user_clan_ranking(hiscores_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = True
    hiscores_0 = module_0.Hiscores(bool_0)
    hiscores_0.get_hiscores_details()


@pytest.mark.xfail(strict=True)
def test_case_6():
    str_0 = "E"
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    hiscores_0.get_leagues_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    list_0 = []
    hiscores_0 = module_0.Hiscores(list_0)
    hiscores_0.get_bosses_groups(hiscores_0, hiscores_0, list_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    bool_0 = True
    hiscores_0 = module_0.Hiscores(bool_0)
    str_0 = "8xD\\N**G@`}(Rk"
    hiscores_0.get_hiscores_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_9():
    str_0 = "baszg*P*?f[?p\x0b@2)i8u"
    hiscores_0 = module_0.Hiscores(str_0)
    hiscores_0.get_ironman_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_10():
    int_0 = -1060
    hiscores_0 = module_0.Hiscores(int_0)
    hiscores_0.get_user_ranking(int_0)


@pytest.mark.xfail(strict=True)
def test_case_11():
    int_0 = 853
    bool_0 = True
    hiscores_0 = module_0.Hiscores(int_0)
    hiscores_0.get_hiscores_details(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_12():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    int_0 = 719
    int_1 = 1955
    bool_0 = True
    hiscores_0.get_group_ironman(int_0, int_0, int_1, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_13():
    bool_0 = True
    hiscores_0 = module_0.Hiscores(bool_0)
    str_0 = "*"
    hiscores_0.get_seasonal_ranking(str_0)


@pytest.mark.xfail(strict=True)
def test_case_14():
    bool_0 = True
    hiscores_0 = module_0.Hiscores(bool_0)
    str_0 = '"'
    hiscores_0.get_seasonal_ranking(str_0, hiscores_0)
