# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.runemetrics as module_0


def test_case_0():
    set_0 = set()
    module_0.Runemetrics(set_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "!\\vxEZF6='V$S\nQSL\x0c:}"
    str_1 = "=fa)ZW.llPd\x0bI\\*v{\x0b:"
    runemetrics_0 = module_0.Runemetrics(str_1)
    int_0 = -585
    runemetrics_0.get_profile(str_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    list_0 = []
    runemetrics_0 = module_0.Runemetrics(list_0)
    runemetrics_0.get_monthly_xp(runemetrics_0, list_0)
