# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.utils.validation as module_0
import builtins as module_1


def test_case_0():
    int_0 = -4273
    none_type_0 = None
    with pytest.raises(ValueError):
        module_0.is_positive_int(int_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"0G"
    bool_0 = False
    module_0.is_boolean(bool_0, bytes_0)
    module_0.is_positive_int(bytes_0, bytes_0)


def test_case_2():
    str_0 = "5c\\`T8n#{Qn"
    module_0.is_non_empty_str(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    tuple_0 = ()
    str_0 = ';@\x0b}E?m"SW'
    module_0.is_non_empty_str(str_0, str_0)
    module_0.is_non_empty_str(tuple_0, tuple_0)


def test_case_4():
    str_0 = "5c\\`T8n#{Qn"
    module_0.is_non_empty_str(str_0, str_0)
    bool_0 = True
    str_1 = "killTimeSeconds"
    module_0.is_boolean(bool_0, str_1)


def test_case_5():
    object_0 = module_1.object()
    str_0 = ""
    with pytest.raises(TypeError):
        module_0.is_boolean(object_0, str_0)


def test_case_6():
    int_0 = 0
    int_1 = 2487
    module_0.is_positive_int(int_1, int_1)
    with pytest.raises(TypeError):
        module_0.is_boolean(int_0, int_0)


def test_case_7():
    str_0 = ""
    with pytest.raises(ValueError):
        module_0.is_non_empty_str(str_0, str_0)
