# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.runemetrics as module_0


def test_case_0():
    bool_0 = False
    module_0.Runemetrics(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "D"
    runemetrics_0 = module_0.Runemetrics(str_0)
    bool_0 = False
    runemetrics_0.get_profile(str_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "V\x0cz#:E# +w-^g$06Q"
    runemetrics_0 = module_0.Runemetrics(str_0)
    bool_0 = False
    runemetrics_0.get_monthly_xp(str_0, bool_0)
