# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.utils.validation as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    str_0 = "dFtMhvKC."
    none_type_0 = module_0.is_boolean(bool_0, str_0)
    str_1 = "[n$"
    module_0.is_non_empty_str(str_1, str_0)
    str_2 = "c4W*FW}Qm3Ax*qv_"
    int_0 = 6
    module_0.is_positive_int(int_0, str_2)
    float_0 = 768.53
    module_0.is_non_empty_str(none_type_0, float_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "}Gc3!E#FHxYE.JV"
    bool_0 = True
    none_type_0 = module_0.is_boolean(bool_0, str_0)
    module_0.is_positive_int(str_0, none_type_0)


def test_case_2():
    str_0 = "=Ao=h5k{Vg.O"
    none_type_0 = module_0.is_non_empty_str(str_0, str_0)
    with pytest.raises(TypeError):
        module_0.is_boolean(none_type_0, none_type_0)


def test_case_3():
    int_0 = -2346
    str_0 = "=Ao=h5k{Vg.O"
    with pytest.raises(TypeError):
        module_0.is_non_empty_str(int_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    tuple_0 = ()
    bool_0 = False
    str_0 = "dFtMhvKC."
    module_0.is_boolean(bool_0, str_0)
    dict_0 = {tuple_0: tuple_0}
    module_0.is_non_empty_str(str_0, dict_0)
    module_0.is_boolean(tuple_0, dict_0)


def test_case_5():
    int_0 = -3967
    str_0 = ",MQ~<j`n"
    with pytest.raises(TypeError):
        module_0.is_boolean(int_0, str_0)


def test_case_6():
    bool_0 = False
    str_0 = "Q]\r2={.V2AP{0w,3}T"
    module_0.is_boolean(bool_0, str_0)
    module_0.is_non_empty_str(str_0, str_0)
    with pytest.raises(ValueError):
        module_0.is_positive_int(bool_0, str_0)


def test_case_7():
    str_0 = "28mW|%nz2-qBh0Kf"
    str_1 = ""
    with pytest.raises(ValueError):
        module_0.is_non_empty_str(str_1, str_0)
