# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import builtins as module_0
import runescape_api.rs3.endpoints.bestiary as module_1
import runescape_api.rs3.models.beast as module_2


def test_case_0():
    object_0 = module_0.object()
    module_1.Bestiary(object_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    object_0 = module_0.object()
    bestiary_0 = module_1.Bestiary(object_0)
    bestiary_0.get_beast_by_id(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "&HdL"
    bestiary_0 = module_1.Bestiary(str_0)
    bestiary_0.get_weakness()


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "\x0c}*w"
    bool_0 = False
    none_type_0 = None
    str_1 = "QX/\x0c'lm'Zp5"
    bool_1 = False
    bool_2 = True
    str_2 = "< VKs\rUTf>&y"
    bool_3 = False
    dict_0 = {str_1: bool_3, str_0: bool_1, str_1: bool_2}
    beast_0 = module_2.Beast(
        none_type_0,
        none_type_0,
        none_type_0,
        str_1,
        bool_0,
        bool_0,
        bool_1,
        none_type_0,
        none_type_0,
        bool_2,
        str_2,
        bool_1,
        str_2,
        none_type_0,
        str_1,
        str_2,
        bool_0,
        bool_1,
        bool_2,
        dict_0,
    )
    var_0 = beast_0.__eq__(bool_0)
    bestiary_0 = module_1.Bestiary(var_0)
    bestiary_0.get_slayer_categories()


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    bestiary_0 = module_1.Bestiary(none_type_0)
    bestiary_0.get_area_names()
