# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import runescape_api.rs3.endpoints.hiscores as module_0


def test_case_0():
    none_type_0 = None
    module_0.Hiscores(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = -2880
    hiscores_0 = module_0.Hiscores(int_0)
    hiscores_0.get_user_clan_ranking(int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "o&z<]"
    int_0 = 6
    hiscores_0 = module_0.Hiscores(int_0)
    hiscores_0.get_bosses_groups(int_0, hiscores_0, int_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = False
    hiscores_0 = module_0.Hiscores(bool_0)
    hiscores_0.get_clan_members_lite(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    str_0 = "hxu<y0"
    hiscores_0.get_seasonal_ranking(str_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    int_0 = 3072
    hiscores_0 = module_0.Hiscores(int_0)
    str_0 = ".k"
    hiscores_0.get_hardcore_ironman_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    str_0 = "1D[B#;9vxk~9"
    hiscores_0.get_ironman_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    hiscores_0.get_hiscores_details()


@pytest.mark.xfail(strict=True)
def test_case_8():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    hiscores_0.get_user_ranking(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_9():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    int_0 = -1869
    hiscores_0.get_group_ironman(int_0, none_type_0, hiscores_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_10():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    var_0 = hiscores_0.__repr__()
    hiscores_0.get_ranking(hiscores_0, var_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_11():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    str_0 = "vfV<OD\x0cMkFr!=p<WU;jD"
    hiscores_0.get_leagues_lite(str_0)


@pytest.mark.xfail(strict=True)
def test_case_12():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    hiscores_0.get_hiscores_lite(hiscores_0)


@pytest.mark.xfail(strict=True)
def test_case_13():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    str_0 = "hxu<y0"
    hiscores_0.get_seasonal_ranking(str_0, hiscores_0)


@pytest.mark.xfail(strict=True)
def test_case_14():
    none_type_0 = None
    hiscores_0 = module_0.Hiscores(none_type_0)
    hiscores_0.get_hiscores_details(hiscores_0)
