APPS_RS = "https://apps.runescape.com"
SECURE_RS = "https://secure.runescape.com"
SERVICES_RS = "http://services.runescape.com"

ITEM_CATEGORIES = {
    0: "Miscellaneous",
    1: "Ammo",
    2: "Arrows",
    3: "Bolts",
    4: "Construction materials",
    5: "Construction products",
    6: "Cooking ingredients",
    7: "Costumes",
    8: "Crafting materials",
    9: "Familiars",
    10: "Farming produce",
    11: "Fletching materials",
    12: "Food and Drink",
    13: "Herblore materials",
    14: "Hunting equipment",
    15: "Hunting Produce",
    16: "Jewellery",
    17: "Mage armour",
    18: "Mage weapons",
    19: "Melee armour - low level",
    20: "Melee armour - mid level",
    21: "Melee armour - high level",
    22: "Melee weapons - low level",
    23: "Melee weapons - mid level",
    24: "Melee weapons - high level",
    25: "Mining and Smithing",
    26: "Potions",
    27: "Prayer armour",
    28: "Prayer materials",
    29: "Range armour",
    30: "Range weapons",
    31: "Runecrafting",
    32: "Runes, Spells and Teleports",
    33: "Seeds",
    34: "Summoning scrolls",
    35: "Tools and containers",
    36: "Woodcutting product",
    37: "Pocket items",
    38: "Stone spirits",
    39: "Salvage",
    40: "Firemaking products",
    41: "Archaeology materials",
    42: "Wood spirits",
    43: "Necromancy armour",
}

SKILLS = [
    "overall",
    "attack",
    "defence",
    "strength",
    "constitution",
    "ranged",
    "prayer",
    "magic",
    "cooking",
    "woodcutting",
    "fletching",
    "fishing",
    "firemaking",
    "crafting",
    "smithing",
    "mining",
    "herblore",
    "agility",
    "thieving",
    "slayer",
    "farming",
    "runecrafting",
    "hunter",
    "construction",
    "summoning",
    "dungeoneering",
    "divination",
    "invention",
    "archaeology",
    "necromancy",
]

ACTIVITIES = [
    "bounty_hunter",
    "bounty_hunter_rogues",
    "dominion_tower",
    "the_crucible",
    "castle_wars_games",
    "ba_attackers",
    "ba_defenders",
    "ba_collectors",
    "ba_healers",
    "duel_tournament",
    "mobilising_armies",
    "conquest",
    "fist_of_guthix",
    "gg_athletics",
    "gg_resource_race",
    "we2_armadyl_lifetime_contribution",
    "we2_bandos_lifetime_contribution",
    "we2_armadyl_pvp_kills",
    "we2_bandos_pvp_kills",
    "heist_guard_level",
    "heist_robber_level",
    "cfp_5_game_average",
    "af15_cow_tipping",
    "af15_rats_killed",
    "runescore",
    "clue_scrolls_easy",
    "clue_scrolls_medium",
    "clue_scrolls_hard",
    "clue_scrolls_elite",
    "clue_scrolls_master",
    "leagues_points",
]